version: 2

jobs:
  build:
    docker:
      - image: cimg/node:14.21@sha256:5375aea82ad62e29304062ba3ba3da36c7095246d180eaee6c68a4d7cef8b0dd
    steps:
      - checkout
      - restore_cache:
          keys:
            - install-dep-cache-{{ checksum "pnpm-lock.yaml" }}
      - restore_cache:
          keys:
            - v-11.0.0-electron
      - run:
          command: npm i --prefix=$HOME/.local -g pnpm@7.1.6
      - run:
          command: pnpm install --frozen-lockfile
      - run:
          command: pnpm compile
      - save_cache:
          key: install-dep-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - run:
          command: node ./test/out/helpers/downloadElectron.js
      - save_cache:
          key: v-11.0.0-electron
          paths:
            - ~/.cache/electron

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - docs
